# Generated by Django 4.1.7 on 2023-04-15 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entry',
            name='emotion',
            field=models.TextField(default='happy'),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
