# Generated by Django 4.1.7 on 2023-04-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_date_entry_emotion_entry_entry_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
